top_srcdir   = /opt/httpd-2.4.46
top_builddir = /opt/httpd-2.4.46
srcdir       = /opt/httpd-2.4.46/modules/mappers
builddir     = /opt/httpd-2.4.46/modules/mappers
VPATH        = /opt/httpd-2.4.46/modules/mappers

include $(top_srcdir)/build/special.mk

