top_srcdir   = /mydata/httpd-2.4.46
top_builddir = /mydata/httpd-2.4.46
srcdir       = /mydata/httpd-2.4.46/modules/mappers
builddir     = /mydata/httpd-2.4.46/modules/mappers
VPATH        = /mydata/httpd-2.4.46/modules/mappers

include $(top_srcdir)/build/special.mk

