top_srcdir   = /mydata/httpd-2.4.46
top_builddir = /mydata/httpd-2.4.46
srcdir       = /mydata/httpd-2.4.46/modules/metadata
builddir     = /mydata/httpd-2.4.46/modules/metadata
VPATH        = /mydata/httpd-2.4.46/modules/metadata

include $(top_srcdir)/build/special.mk

