top_srcdir   = /opt/httpd-2.4.46
top_builddir = /opt/httpd-2.4.46
srcdir       = /opt/httpd-2.4.46/modules/metadata
builddir     = /opt/httpd-2.4.46/modules/metadata
VPATH        = /opt/httpd-2.4.46/modules/metadata

include $(top_srcdir)/build/special.mk

