top_srcdir   = /opt/httpd-2.4.46
top_builddir = /opt/httpd-2.4.46
srcdir       = /opt/httpd-2.4.46/modules/loggers
builddir     = /opt/httpd-2.4.46/modules/loggers
VPATH        = /opt/httpd-2.4.46/modules/loggers

include $(top_srcdir)/build/special.mk

