top_srcdir   = /mydata/httpd-2.4.46
top_builddir = /mydata/httpd-2.4.46
srcdir       = /mydata/httpd-2.4.46/modules/loggers
builddir     = /mydata/httpd-2.4.46/modules/loggers
VPATH        = /mydata/httpd-2.4.46/modules/loggers

include $(top_srcdir)/build/special.mk

