top_srcdir   = /mydata/httpd-2.4.46
top_builddir = /mydata/httpd-2.4.46
srcdir       = /mydata/httpd-2.4.46/modules/generators
builddir     = /mydata/httpd-2.4.46/modules/generators
VPATH        = /mydata/httpd-2.4.46/modules/generators

include $(top_srcdir)/build/special.mk

