top_srcdir   = /opt/httpd-2.4.46
top_builddir = /opt/httpd-2.4.46
srcdir       = /opt/httpd-2.4.46/modules/generators
builddir     = /opt/httpd-2.4.46/modules/generators
VPATH        = /opt/httpd-2.4.46/modules/generators

include $(top_srcdir)/build/special.mk

