top_srcdir   = /mydata/httpd-2.4.46
top_builddir = /mydata/httpd-2.4.46
srcdir       = /mydata/httpd-2.4.46/modules/echo
builddir     = /mydata/httpd-2.4.46/modules/echo
VPATH        = /mydata/httpd-2.4.46/modules/echo

include $(top_srcdir)/build/special.mk

