top_srcdir   = /mydata/httpd-2.4.46
top_builddir = /mydata/httpd-2.4.46
srcdir       = /mydata/httpd-2.4.46/modules/filters
builddir     = /mydata/httpd-2.4.46/modules/filters
VPATH        = /mydata/httpd-2.4.46/modules/filters

include $(top_srcdir)/build/special.mk

