top_srcdir   = /opt/httpd-2.4.46
top_builddir = /opt/httpd-2.4.46
srcdir       = /opt/httpd-2.4.46/modules/filters
builddir     = /opt/httpd-2.4.46/modules/filters
VPATH        = /opt/httpd-2.4.46/modules/filters

include $(top_srcdir)/build/special.mk

