top_srcdir   = /opt/httpd-2.4.46
top_builddir = /opt/httpd-2.4.46
srcdir       = /opt/httpd-2.4.46/modules/aaa
builddir     = /opt/httpd-2.4.46/modules/aaa
VPATH        = /opt/httpd-2.4.46/modules/aaa

include $(top_srcdir)/build/special.mk

