top_srcdir   = /mydata/httpd-2.4.46
top_builddir = /mydata/httpd-2.4.46
srcdir       = /mydata/httpd-2.4.46/modules/aaa
builddir     = /mydata/httpd-2.4.46/modules/aaa
VPATH        = /mydata/httpd-2.4.46/modules/aaa

include $(top_srcdir)/build/special.mk

