top_srcdir   = /mydata/httpd-2.4.46
top_builddir = /mydata/httpd-2.4.46
srcdir       = /mydata/httpd-2.4.46/server/mpm/event
builddir     = /mydata/httpd-2.4.46/server/mpm/event
VPATH        = /mydata/httpd-2.4.46/server/mpm/event
include $(top_srcdir)/build/special.mk
