top_srcdir   = /opt/httpd-2.4.46
top_builddir = /opt/httpd-2.4.46
srcdir       = /opt/httpd-2.4.46/server/mpm/event
builddir     = /opt/httpd-2.4.46/server/mpm/event
VPATH        = /opt/httpd-2.4.46/server/mpm/event
include $(top_srcdir)/build/special.mk
