top_srcdir   = /mydata/httpd-2.4.46
top_builddir = /mydata/httpd-2.4.46
srcdir       = /mydata/httpd-2.4.46/modules/cache
builddir     = /mydata/httpd-2.4.46/modules/cache
VPATH        = /mydata/httpd-2.4.46/modules/cache

include $(top_srcdir)/build/special.mk

