top_srcdir   = /opt/httpd-2.4.46
top_builddir = /opt/httpd-2.4.46
srcdir       = /opt/httpd-2.4.46/modules/cache
builddir     = /opt/httpd-2.4.46/modules/cache
VPATH        = /opt/httpd-2.4.46/modules/cache

include $(top_srcdir)/build/special.mk

