top_srcdir   = /opt/httpd-2.4.46
top_builddir = /opt/httpd-2.4.46
srcdir       = /opt/httpd-2.4.46/os
builddir     = /opt/httpd-2.4.46/os
VPATH        = /opt/httpd-2.4.46/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
