top_srcdir   = /mydata/httpd-2.4.46
top_builddir = /mydata/httpd-2.4.46
srcdir       = /mydata/httpd-2.4.46/os
builddir     = /mydata/httpd-2.4.46/os
VPATH        = /mydata/httpd-2.4.46/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
