top_srcdir   = /mydata/httpd-2.4.46
top_builddir = /mydata/httpd-2.4.46
srcdir       = /mydata/httpd-2.4.46/modules/arch/unix
builddir     = /mydata/httpd-2.4.46/modules/arch/unix
VPATH        = /mydata/httpd-2.4.46/modules/arch/unix

include $(top_srcdir)/build/special.mk

