top_srcdir   = /opt/httpd-2.4.46
top_builddir = /opt/httpd-2.4.46
srcdir       = /opt/httpd-2.4.46/modules/arch/unix
builddir     = /opt/httpd-2.4.46/modules/arch/unix
VPATH        = /opt/httpd-2.4.46/modules/arch/unix

include $(top_srcdir)/build/special.mk

