top_srcdir   = /mydata/httpd-2.4.46
top_builddir = /mydata/httpd-2.4.46
srcdir       = /mydata/httpd-2.4.46/modules/dav/main
builddir     = /mydata/httpd-2.4.46/modules/dav/main
VPATH        = /mydata/httpd-2.4.46/modules/dav/main
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
