top_srcdir   = /mydata/httpd-2.4.46
top_builddir = /mydata/httpd-2.4.46
srcdir       = /mydata/httpd-2.4.46/modules/core
builddir     = /mydata/httpd-2.4.46/modules/core
VPATH        = /mydata/httpd-2.4.46/modules/core

include $(top_srcdir)/build/special.mk

