top_srcdir   = /opt/httpd-2.4.46
top_builddir = /opt/httpd-2.4.46
srcdir       = /opt/httpd-2.4.46/modules/core
builddir     = /opt/httpd-2.4.46/modules/core
VPATH        = /opt/httpd-2.4.46/modules/core

include $(top_srcdir)/build/special.mk

