top_srcdir   = /opt/httpd-2.4.46
top_builddir = /opt/httpd-2.4.46
srcdir       = /opt/httpd-2.4.46/modules/http
builddir     = /opt/httpd-2.4.46/modules/http
VPATH        = /opt/httpd-2.4.46/modules/http

include $(top_srcdir)/build/special.mk

