top_srcdir   = /mydata/httpd-2.4.46
top_builddir = /mydata/httpd-2.4.46
srcdir       = /mydata/httpd-2.4.46/modules/http
builddir     = /mydata/httpd-2.4.46/modules/http
VPATH        = /mydata/httpd-2.4.46/modules/http

include $(top_srcdir)/build/special.mk

