top_srcdir   = /opt/httpd-2.4.46
top_builddir = /opt/httpd-2.4.46
srcdir       = /opt/httpd-2.4.46/server/mpm
builddir     = /opt/httpd-2.4.46/server/mpm
VPATH        = /opt/httpd-2.4.46/server/mpm

SUBDIRS = $(MPM_SUBDIRS)

include $(top_builddir)/build/rules.mk
