top_srcdir   = /mydata/httpd-2.4.46
top_builddir = /mydata/httpd-2.4.46
srcdir       = /mydata/httpd-2.4.46/server/mpm
builddir     = /mydata/httpd-2.4.46/server/mpm
VPATH        = /mydata/httpd-2.4.46/server/mpm

SUBDIRS = $(MPM_SUBDIRS)

include $(top_builddir)/build/rules.mk
